import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Reporting App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen min-w-full bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
